version: "3.3"

services:
  traefik:
    image: "traefik:v2.2"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api.insecure
      - --providers.docker.exposedbydefault=false
      #swarm
      - --providers.docker.swarmmode=true
    ports:
      - "80:80"
      - "8080:8080"
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public
  
  bio:
    image: nginx
    #command:
      #- --port=80
    volumes: 
        - /sites/bio/www:/usr/share/nginx/html
    deploy:
      labels:
          - traefik.enable=true
          - traefik.http.routers.bio.rule=Host(`biostrefa.org`)
          - traefik.http.services.bio.loadbalancer.server.port=80
    networks:
      - public
  avizi:
    image: nginx
    #command:
      #- --port=80
    volumes: 
        - /sites/avizi/www:/usr/share/nginx/html
    deploy:
      labels:
          - traefik.enable=true
          - traefik.http.routers.avizi.rule=Host(`avizi.org`)
          - traefik.http.services.avizi.loadbalancer.server.port=80
    networks:
      - public
  api:
    image: containous/whoami:v1.3.0
    command:
      - --port=1337 # Our service listens on 1337
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`api.avizi.org`)
        - traefik.http.services.api.loadbalancer.server.port=1337
    networks:
      - public

networks:
  public:
    driver: overlay
    attachable: true
    